# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gaea Project
tagline:          'por Eric Parga'
description:      'Compendio del universo literario de Eric Parga.</br><small>Fork del Hyde de <a href="https://twitter.com/mdo" target="_blank">@mdo</a> para <a href="http://jekyllrb.com" target="_blank">Jekyll</a>.</small>'
url:              http://hacknug.github.io/
baseurl:          /

author:
  name:           'Nestor Vera'
  url:            https://twitter.com/hack_nug

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Gems
gems:             [jekyll-paginate, jekyll-gist]

# Colecciones
collections:
  personajes:
    output:       true
  drogas:
    titulo:        "Estoy En Puertomarte Sin Hilda"
    output:       true
  religiones:
    output:       true
  microrrelatos:
    output:       true
  fauna-y-flora:
    output:       true
  tecnologia:
    output:       true

# Google Map Embed
google_map_zoom: 16               # 1=Global zoom 18=Street Level
google_map_view: satellite        # hybrid | satellite | roadmap
google_map_height: 450            # Default map height. Width adjusts to container.
google_api_key: "AIzaSyDmt_iRsE8kQ1glUPC2GZpNLBsw1Laj9_0" # https://code.google.com/apis/console/
