# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gaea Project
tagline:          'por Eric Parga'
description:      'Compendio del universo literario de Eric Parga.</br><small>Fork del Hyde de <a href="https://twitter.com/mdo" target="_blank">@mdo</a> para <a href="http://jekyllrb.com" target="_blank">Jekyll</a>.</small>'
url:              http://hacknug.github.io/
baseurl:          /

author:
  name:           'Nestor Vera'
  url:            https://twitter.com/hack_nug

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  personajes:
    output:       true
  drogas:
    title:        "Estoy En Puertomarte Sin Hilda"
    output:       true
  religiones:
    output:       true
  microrrelatos:
    output:       true
  fauna-y-flora:
    output:       true
  tecnologia:
    output:       true
